# Generated by Django 4.1.5 on 2023-03-03 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=100, unique=True)),
                ("product_slug", models.SlugField(max_length=100)),
                ("product_description", models.TextField(blank=True, max_length=400)),
                ("product_price", models.IntegerField()),
                ("product_stock", models.IntegerField()),
                ("product_isavilabe", models.BooleanField(default=True)),
                ("product_image", models.ImageField(upload_to="photos/products")),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
            ],
        ),
    ]
