# Generated by Django 4.1.5 on 2023-02-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoryName", models.CharField(max_length=50, unique=True)),
                ("categorySlug", models.CharField(max_length=50, unique=True)),
                ("categoryDescription", models.TextField(blank=True, max_length=200)),
                (
                    "categoryImage",
                    models.ImageField(blank=True, upload_to="photos/categories"),
                ),
            ],
        ),
    ]
