# Generated by Django 4.1.5 on 2023-03-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="user",),
        migrations.AddField(
            model_name="cart",
            name="cart_id",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cart",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem", name="quantity", field=models.IntegerField(),
        ),
    ]
